name: Scheduled Postman Run

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run "API Testing.postman_collection" \
             --reporters cli,json,html \
             --reporter-html-export newman-report.html

      # ✅ New step to verify that the HTML report exists
      - name: List files
        run: ls -la

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: newman-report.html
